# Generated by Django 4.2.18 on 2025-01-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('main_category', models.CharField(max_length=50)),
                ('nutrient_standard', models.CharField(max_length=20)),
                ('energy', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('carbs', models.FloatField()),
                ('sugar', models.FloatField()),
                ('fiber', models.FloatField()),
                ('sodium', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('saturated_fat', models.FloatField()),
                ('trans_fat', models.FloatField()),
                ('weight', models.CharField(max_length=20)),
            ],
        ),
    ]
